name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the main branch
  # Using a different branch name? Replace main with your branch’s name
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Display node_modules path
        run: |
          echo "Current directory:"
          pwd
          echo "node_modules path:"
          find . -name "node_modules" -type d
        
     # - name: Copy modified Icon.ts to node_modules
     #   run: |
     #     cp node_modules/@astrojs/starlight/components/Icon.ts node_modules/@astrojs/starlight/components/Icon.ts

      - name: Install, build, and upload your site output
        uses: withastro/action@v4

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
